networks:
  net:
    driver: bridge

services:
  mysql:
    image: mysql:8.0.43-debian
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ptudwnc
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    ports:
      - '3306:3306'
    restart: always

    networks:
      - net
