input {
  tcp {
    port => 5000
    codec => plain
  }
  beats {
    port => 5044
  }
}

filter {
  json {
    source => "message"
    target => "parsed_message"
    remove_field => ["message"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "week03-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
